Repository AY2122S2-CS2103T-T09-1/tp, pull requests merged in 2022-04, with the labels that each got.

#260 Fix bug on unmark command and make sort by name case insensitive
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/commands/sort/ComparatorFactory.java
  src/main/java/seedu/address/model/task/Name.java
Labels: type.Task

#267 Fix issue where text on the context menu is white
  docs/UserGuide.md
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/HarmoniaTheme.css
  src/main/resources/view/TaskListCard.fxml
Labels: type.Bug

#268 Fix UG problem in Section 1.4 and improve annotated UI
  docs/UserGuide.md
  docs/images/AnnotatedUi.png
  docs/images/TaskCard.png
Labels: type.Bug

#265 Fix bug for list tags
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TagList.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Bug

#271 Add 50-character constraint on tag, and add tag tests
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Labels: type.Enhancement

#272 Fix error messages for mark and unmark, ensured that command wouldnt work if any parameter is invalid
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
Labels: type.Bug

#277 Fix name, description and tag truncation problem when resizing GUI
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/HarmoniaTheme.css
  src/main/resources/view/TaskListCard.fxml
Labels: type.Bug

#275 Update tag contraints to only allow alphanumeric characters
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Bug

#276 Update UG for list tags
  docs/UserGuide.md
Labels: type.Bug

#287 Update PPP
  docs/team/nicollegann.md
Labels: type.Task

#284 Update PPP
  docs/team/sbhbenjamin.md
Labels: type.Task

#288 Add Joeie's PPP
  docs/team/joeietao.md
Labels: type.Task

#289 Update Thikhina's PPP
  docs/team/thikhinab.md
Labels: type.Task

#283 Add model segment of the developer's guide
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: type.Task

#278 Add and standardise images in the UG
  docs/UserGuide.md
  docs/images/Ui-AddTask.png
  docs/images/Ui-FindStartDate.png
  docs/images/Ui-MarkTask.png
  docs/images/Ui-MassUnmarkTasks.png
  docs/images/Ui-SortPriority.png
  docs/images/Ui-UnmarkTask.png
  docs/images/Ui.png
  docs/images/UserGuide-add.png
  docs/images/UserGuide-massmark-after.png
  docs/images/UserGuide-massunmark-after.png
Labels: type.Enhancement, type.Task

#281 Fix DeleteCommand
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/MassOpsParser.java
Labels: type.Bug

#292 Make PPP more concise
  docs/team/sbhbenjamin.md
Labels: type.Enhancement

#293 Add note for duplicate tags in UG
  docs/UserGuide.md
Labels: type.Bug

#295 Update Architecture segment of developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: type.Task

#290 Clarify about duplicate paramters and preservation of sort order
  docs/UserGuide.md
Labels: type.Bug

#317 Refactor model tests
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/task/CompletionStatusTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/model/task/DescriptionTest.java
  src/test/java/seedu/address/model/task/NameTest.java
  src/test/java/seedu/address/model/task/PriorityTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: type.Enhancement

#318 Add credit for code reuse
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#299 Add tests for delete command
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Task

#300 Fix tests in JsonTaskListStorageTest and JsonSerializableTaskListTest
  src/test/data/JsonSerializableTaskListTest/typicalTaskList.json
  src/test/java/seedu/address/storage/JsonSerializableTaskListTest.java
  src/test/java/seedu/address/storage/JsonTaskListStorageTest.java
Labels: type.Bug

#325 Fix and enhance UG
  docs/UserGuide.md
Labels: type.Bug, type.Enhancement

#319 Test for MassOps
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/MassOpsParser.java
  src/test/data/JsonSerializableTaskListTest/typicalTaskList.json
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/HarmoniaParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MassOpsParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#320 Add implementation details for list tags and undo/redo in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ListTagsSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/ListTagsSequenceDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: type.Task

#322 Fix tag such that it is case-insensitive
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Bug

#326 Update message usage of delete, mark and unmark to match user guide
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
Labels: type.Bug

#331 Update PPP
  docs/team/nicollegann.md
Labels: type.Task

#342 Update use cases in developer guide
  docs/DeveloperGuide.md
Labels: type.Bug

#345 Update sample data to match screenshot in UG
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug

#296 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Task

#351 Fix UML class diagram format
  docs/diagrams/PriorityDiagram.puml
  docs/images/PriorityDiagram.png
Labels: type.Bug
