Repository AY2122S2-CS2103T-T09-1/tp, pull requests merged in 2022-03, with the labels that each got.

#100 Modify model to support tasks
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTaskList.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/task/CompletionStatus.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Description.java
  src/main/java/seedu/address/model/task/Name.java
  src/main/java/seedu/address/model/task/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
Labels: type.Task

#107 Add use cases and update format
  docs/DeveloperGuide.md
Labels: type.Bug, type.Task

#127 Integrate V1.2-Evolution
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/task/Description.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Task, priority.High

#128 Update testutil
  src/test/java/seedu/address/logic/parser/HarmoniaParserTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskListBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#147 Add tests for the model
  src/main/java/seedu/address/model/task/Description.java
  src/main/java/seedu/address/model/task/Name.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/TaskListTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/task/CompletionStatusTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/model/task/DescriptionTest.java
  src/test/java/seedu/address/model/task/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/NameTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#150 Test UnamrkCommand and UnmarkCommandParser
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/test/data/JsonSerializableTaskListTest/typicalTaskList.json
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/HarmoniaParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#149 Update JsonUserPrefsStorageTest and add JsonTaskListStorageTest
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonTaskListStorageTest/invalidAndValidTaskTaskList.json
  src/test/data/JsonTaskListStorageTest/invalidTaskTaskList.json
  src/test/data/JsonTaskListStorageTest/notJsonFormatTaskList.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonTaskListStorageTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Task

#159 Hotfix for failing storage test
  src/test/data/JsonTaskListStorageTest/invalidTaskTaskList.json
Labels: type.Bug, priority.High

#158 Add description of Priority implementation in Developers Guide
  docs/DeveloperGuide.md
  docs/diagrams/PriorityDiagram.puml
  docs/images/PriorityDiagram.png
Labels: type.Task

#163 Add description of search by tags implementation in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/SearchByTagSequenceDiagram.puml
  docs/images/SearchByTagSequenceDiagram.png
Labels: type.Task

#171 Update DeveloperGuide for MassOps
  docs/DeveloperGuide.md
  docs/diagrams/MassOpsMark.puml
  docs/diagrams/MassOpsUnmark.puml
  docs/images/MassOpsMark.png
  docs/images/MassOpsUnmark.png
  src/main/java/seedu/address/ui/TaskCard.java
Labels: type.Task

#153 Add priority to tasks
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Priority.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableTaskListTest/duplicateTaskTaskList.json
  src/test/data/JsonSerializableTaskListTest/typicalTaskList.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/task/PriorityTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#174 Comment out failing test cases
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/storage/JsonSerializableTaskListTest.java
  src/test/java/seedu/address/storage/JsonTaskListStorageTest.java
Labels: type.Bug, priority.High, severity.High

#165 Add assertions to the gradle file
  build.gradle
Labels: type.Task

#184 Add the about segment of the User Guide
  docs/UserGuide.md
  docs/images/Harmonia.png
Labels: type.Task

#183 update user guide add, list, mark, unmark
  build.gradle
  docs/UserGuide.md
  docs/images/UserGuide-add.png
Labels: type.Task

#186 Update User Guide: Getting Started and Notes about command format
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/UiMockup.png
Labels: type.Task

#189 Update user guide
  docs/UserGuide.md
Labels: type.Task

#193 Update user guide
  docs/UserGuide.md
Labels: type.Task

#194 Fix TOC formatting, return to top anchors and typography segment
  docs/UserGuide.md
Labels: type.Bug, type.Task

#195 Fix site-wide setting for documentation
  docs/_sass/minima/_base.scss
Labels: type.Bug

#201 Fix bug where add command throws exception silently due to priority
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: type.Bug

#203 Improve GUI
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/HarmoniaTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: type.Enhancement, type.Task

#204 Update message usage for add command
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug

#191 Add massOps for delete and fixed the output message of mark/unmark
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/MassOpsParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/test/java/seedu/address/logic/parser/HarmoniaParserTest.java
Labels: type.Enhancement

#207 Update GUI explanation and screenshots of GUI
  docs/UserGuide.md
  docs/images/AnnotatedUi.png
  docs/images/Ui.png
  docs/images/UserGuide-add.png
  docs/index.md
Labels: type.Enhancement, type.Task

#216 Replace mark and unmark photos
  docs/UserGuide.md
  docs/images/UserGuide-mark.png
  docs/images/UserGuide-massmark-after.png
  docs/images/UserGuide-massunmark-after.png
  docs/images/UserGuide-unmark.png
Labels: type.Task
